### ISSUE TITLE
Homebrew installer has moved

### ISSUE THREAD

**Issue by lintaoSuper** [zhuchaowe/ModelCoder#1]
1.Installation Homebrew

If you have homebrew installed, just jump to the second step

ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"

 The Homebrew installer has moved! Please instead run:
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

**Comment by zhuchaowe** [comment]
Think you for this issue,I plan to rewrite this program by golang for better installation experience
